/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante_la_prosperidad_camilo_miguel;

import java.io.*;
import java.util.logging.*;
import javax.swing.table.DefaultTableModel;


 

public class Cocina extends javax.swing.JFrame {

    /**
     * Creates new form Cocina
     */
    String nombreM = "";
    int cont, MesaN;
    String plato1="", plato2="", plato3="", plato4="", plato5="", bebida1="", bebida2="", bebida3="", postre1="", postre2="", postre3="", postre4="";
    int cantpl1, cantpl2, cantpl3,cantpl4, cantpl5, cantb1, cantb2, cantb3, cantpo1, cantpo2, cantpo3, cantpo4, cantpo5;
    float preciopl1, preciopl2, preciopl3, preciopl4, preciopl5, preciob1, preciob2, preciob3, preciopo1, preciopo2, preciopo3, preciopo4;
    
    public Cocina() {
        initComponents();
    }
    
    File archivo = new File("C:\\Users\\Camilo D\\Documents\\Restaurante_La_Prosperidad_Camilo_Miguel\\src\\Archivos\\Pedidos.txt");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bda = new javax.swing.JFileChooser();
        Comanda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ped = new javax.swing.JTable();
        jSplitPane1 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();
        ACTUALIZAR = new javax.swing.JButton();
        pedidoMesa = new javax.swing.JLabel();
        meseroCargo = new javax.swing.JLabel();

        bda.setBackground(java.awt.Color.white);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");
        setMinimumSize(new java.awt.Dimension(280, 390));
        setPreferredSize(new java.awt.Dimension(280, 390));
        setResizable(false);
        setSize(new java.awt.Dimension(280, 390));

        Ped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Cantidad", "Precio Un."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Ped);
        if (Ped.getColumnModel().getColumnCount() > 0) {
            Ped.getColumnModel().getColumn(0).setResizable(false);
            Ped.getColumnModel().getColumn(1).setResizable(false);
            Ped.getColumnModel().getColumn(2).setResizable(false);
        }

        jSplitPane1.setFocusable(false);

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(jButton1);

        ACTUALIZAR.setText("ACTUALIZAR");
        ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUALIZARActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(ACTUALIZAR);

        javax.swing.GroupLayout ComandaLayout = new javax.swing.GroupLayout(Comanda);
        Comanda.setLayout(ComandaLayout);
        ComandaLayout.setHorizontalGroup(
            ComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        ComandaLayout.setVerticalGroup(
            ComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComandaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pedidoMesa.setText("Pedido de la mesa #: ");

        meseroCargo.setText("Mesero a cargo: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Comanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedidoMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meseroCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pedidoMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meseroCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Comanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Comanda.getAccessibleContext().setAccessibleName("Mesa #1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void generarMatriz(){
        int conta, pos=0;
        conta= this.cont;
        DefaultTableModel model = (DefaultTableModel) Ped.getModel();
        model.setRowCount(conta);
        model.setColumnCount(3);
        if (this.plato1.equals("Kati Roll")) {
            Ped.setValueAt(this.plato1, pos, 0);
            Ped.setValueAt(this.cantpl1, pos, 1);
            Ped.setValueAt(this.preciopl1, pos, 2);
            modificarArchivo(this.plato1 , this.cantpl1, this.preciopl1);
            pos=pos+1;
        }
        if (this.plato2.equals("Papada de Cerdo")) {
            Ped.setValueAt(this.plato2, pos, 0);
            Ped.setValueAt(this.cantpl2, pos, 1);
            Ped.setValueAt(this.preciopl2, pos, 2);
            modificarArchivo(this.plato2 , this.cantpl2, this.preciopl2);
            pos=pos+1;
        }
        if (this.plato3.equals("Cabracho con Alcachofas")) {
            Ped.setValueAt(this.plato3, pos, 0);
            Ped.setValueAt(this.cantpl3, pos, 1);
            Ped.setValueAt(this.preciopl3, pos, 2);
            modificarArchivo(this.plato3 , this.cantpl3, this.preciopl3);
            pos=pos+1;
        }
        if (this.plato4.equals("Solomillo de Cerdo Hojaldrado")) {
            Ped.setValueAt(this.plato4, pos, 0);
            Ped.setValueAt(this.cantpl4, pos, 1);
            Ped.setValueAt(this.preciopl4, pos, 2);
            modificarArchivo(this.plato4 , this.cantpl4, this.preciopl4);
            pos=pos+1;
        }
        if (this.plato5.equals("Spaghetti al Ragú")) {
            Ped.setValueAt(this.plato5, pos, 0);
            Ped.setValueAt(this.cantpl5, pos, 1);
            Ped.setValueAt(this.preciopl5, pos, 2);
            modificarArchivo(this.plato5 , this.cantpl5, this.preciopl5);
            pos=pos+1;
        }
        if (this.bebida1.equals("Coca Cola")) {
            Ped.setValueAt(this.bebida1, pos, 0);
            Ped.setValueAt(this.cantb1, pos, 1);
            Ped.setValueAt(this.preciob1, pos, 2);
            modificarArchivo(this.bebida1 , this.cantb1, this.preciob1);
            pos=pos+1;
        }
        if (this.bebida2.equals("Gaseosa")) {
            Ped.setValueAt(this.bebida2, pos, 0);
            Ped.setValueAt(this.cantb2, pos, 1);
            Ped.setValueAt(this.preciob2, pos, 2);
            modificarArchivo(this.bebida2 , this.cantb2, this.preciob2);
            pos=pos+1;
        }
        if (this.bebida3.equals("Jugos Naturales")) {
            Ped.setValueAt(this.bebida3, pos, 0);
            Ped.setValueAt(this.cantb3, pos, 1);
            Ped.setValueAt(this.preciob3, pos, 2);
            modificarArchivo(this.bebida3 , this.cantb3, this.preciob3);
            pos=pos+1;
        }
        if (this.postre1.equals("Manzana Templada")) {
            Ped.setValueAt(this.postre1, pos, 0);
            Ped.setValueAt(this.cantpo1, pos, 1);
            Ped.setValueAt(this.preciopo1, pos, 2);
            modificarArchivo(this.postre1 , this.cantpo1, this.preciopo1);
            pos=pos+1;
        }
        if (this.postre2.equals("Tiramisú Crujiente")) {
            Ped.setValueAt(this.postre2, pos, 0);
            Ped.setValueAt(this.cantpo2, pos, 1);
            Ped.setValueAt(this.preciopo2, pos, 2);
            modificarArchivo(this.postre2 , this.cantpo2, this.preciopo2);
            pos=pos+1;
        }
        if (this.postre3.equals("Exótico")) {
            Ped.setValueAt(this.postre3, pos, 0);
            Ped.setValueAt(this.cantpo3, pos, 1);
            Ped.setValueAt(this.preciopo3, pos, 2);
            modificarArchivo(this.postre3 , this.cantpo3, this.preciopo3);
            pos=pos+1;
        }
        if (this.postre4.equals("Minitarta Selva Negra")) {
            Ped.setValueAt(this.postre4, pos, 0);
            Ped.setValueAt(this.cantpo4, pos, 1);
            Ped.setValueAt(this.preciopo4, pos, 2);
            modificarArchivo(this.postre4 , this.cantpo4, this.preciopo4);
            pos=pos+1;
        }
        Ped.setModel(model);
        /*
        this.Ped = new JTable(model){
            @Override
            public String getToolTipText( MouseEvent e ){
                int row = rowAtPoint( e.getPoint() );
                int column = columnAtPoint( e.getPoint() );
                Object value = getValueAt(row, column);
                return value == null ? null : value.toString();
            }
        };
        this.jScrollPane1.setViewportView(Ped);
        */
    }
    
    private void ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUALIZARActionPerformed
        generarMatriz();
        pedidoMesa.setText("Pedido de la mesa #: " + MesaN + ".");
        meseroCargo.setText("Mesero a cargo: " + nombreM + ".");
    }//GEN-LAST:event_ACTUALIZARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void modificarArchivo(String plato, int cantidad, float precio){
        
        try(FileWriter bw = new FileWriter(archivo, true)){
            Object PL = plato;
            Object CA = cantidad;
            Object PR = precio;
            bw.write( PL + ", " + CA + ", " + PR + "\r" + "\n" );
        }catch(NullPointerException ex){
        
        } catch (IOException ex) {
            Logger.getLogger(Cocina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cocina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZAR;
    private javax.swing.JPanel Comanda;
    public javax.swing.JTable Ped;
    private javax.swing.JFileChooser bda;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel meseroCargo;
    private javax.swing.JLabel pedidoMesa;
    // End of variables declaration//GEN-END:variables
}
