package restaurante_la_prosperidad_camilo_miguel;

import java.io.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;

public class Cocina extends javax.swing.JFrame {

    /**
     * Creates new form Cocina
     */
    String nombreM = "", horaP = "", TP = "", nombreC;
    int cont, MesaN, tp, cedulaC;
    String plato1="", plato2="", plato3="", plato4="", plato5="", bebida1="", bebida2="", bebida3="", postre1="", postre2="", postre3="", postre4="";
    int cantpl1, cantpl2, cantpl3,cantpl4, cantpl5, cantb1, cantb2, cantb3, cantpo1, cantpo2, cantpo3, cantpo4, cantpo5;
    float preciopl1, preciopl2, preciopl3, preciopl4, preciopl5, preciob1, preciob2, preciob3, preciopo1, preciopo2, preciopo3, preciopo4;
    
    public Cocina() {
        initComponents();
    }
    
    File archivo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Comanda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ped = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pedidoMesa = new javax.swing.JLabel();
        meseroCargo = new javax.swing.JLabel();
        totalPagar = new javax.swing.JLabel();
        horaPedido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("COCINA");
        setMinimumSize(new java.awt.Dimension(280, 385));
        setPreferredSize(new java.awt.Dimension(280, 385));
        setResizable(false);
        setSize(new java.awt.Dimension(280, 385));

        Ped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Cant.", "Precio Un."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Ped);
        if (Ped.getColumnModel().getColumnCount() > 0) {
            Ped.getColumnModel().getColumn(0).setResizable(false);
            Ped.getColumnModel().getColumn(1).setResizable(false);
            Ped.getColumnModel().getColumn(1).setPreferredWidth(10);
            Ped.getColumnModel().getColumn(2).setResizable(false);
            Ped.getColumnModel().getColumn(2).setPreferredWidth(15);
        }

        jButton1.setText("COCINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ComandaLayout = new javax.swing.GroupLayout(Comanda);
        Comanda.setLayout(ComandaLayout);
        ComandaLayout.setHorizontalGroup(
            ComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComandaLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        ComandaLayout.setVerticalGroup(
            ComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComandaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pedidoMesa.setText("Pedido de la mesa #: ");

        meseroCargo.setText("Mesero a cargo: ");

        totalPagar.setText("Total a pagar: ");

        horaPedido.setText("Hora en que se realizó el pedido: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Comanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedidoMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meseroCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(horaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(horaPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pedidoMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meseroCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Comanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Comanda.getAccessibleContext().setAccessibleName("Mesa #1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void generarMatriz(){
        int conta, pos=0;
        conta= this.cont;
        float totalAPagar = 0;
        DefaultTableModel model = (DefaultTableModel) Ped.getModel();
        model.setRowCount(conta);
        modificarArchivo("",2);
        modificarArchivo(MesaN);
        if (this.plato1.equals("Kati Roll")) {
            Ped.setValueAt(this.plato1, pos, 0);
            Ped.setValueAt(this.cantpl1, pos, 1);
            Ped.setValueAt(this.preciopl1, pos, 2);
            modificarArchivo(this.plato1 , this.cantpl1, this.preciopl1);
            pos=pos+1;
        }
        if (this.plato2.equals("Papada de Cerdo")) {
            Ped.setValueAt(this.plato2, pos, 0);
            Ped.setValueAt(this.cantpl2, pos, 1);
            Ped.setValueAt(this.preciopl2, pos, 2);
            modificarArchivo(this.plato2 , this.cantpl2, this.preciopl2);
            pos=pos+1;
        }
        if (this.plato3.equals("Cabracho con Alcachofas")) {
            Ped.setValueAt(this.plato3, pos, 0);
            Ped.setValueAt(this.cantpl3, pos, 1);
            Ped.setValueAt(this.preciopl3, pos, 2);
            modificarArchivo(this.plato3 , this.cantpl3, this.preciopl3);
            pos=pos+1;
        }
        if (this.plato4.equals("Solomillo de Cerdo Hojaldrado")) {
            Ped.setValueAt(this.plato4, pos, 0);
            Ped.setValueAt(this.cantpl4, pos, 1);
            Ped.setValueAt(this.preciopl4, pos, 2);
            modificarArchivo(this.plato4 , this.cantpl4, this.preciopl4);
            pos=pos+1;
        }
        if (this.plato5.equals("Spaghetti al Ragú")) {
            Ped.setValueAt(this.plato5, pos, 0);
            Ped.setValueAt(this.cantpl5, pos, 1);
            Ped.setValueAt(this.preciopl5, pos, 2);
            modificarArchivo(this.plato5 , this.cantpl5, this.preciopl5);
            pos=pos+1;
        }
        if (this.bebida1.equals("Coca Cola")) {
            Ped.setValueAt(this.bebida1, pos, 0);
            Ped.setValueAt(this.cantb1, pos, 1);
            Ped.setValueAt(this.preciob1, pos, 2);
            modificarArchivo(this.bebida1 , this.cantb1, this.preciob1);
            pos=pos+1;
        }
        if (this.bebida2.equals("Gaseosa")) {
            Ped.setValueAt(this.bebida2, pos, 0);
            Ped.setValueAt(this.cantb2, pos, 1);
            Ped.setValueAt(this.preciob2, pos, 2);
            modificarArchivo(this.bebida2 , this.cantb2, this.preciob2);
            pos=pos+1;
        }
        if (this.bebida3.equals("Jugos Naturales")) {
            Ped.setValueAt(this.bebida3, pos, 0);
            Ped.setValueAt(this.cantb3, pos, 1);
            Ped.setValueAt(this.preciob3, pos, 2);
            modificarArchivo(this.bebida3 , this.cantb3, this.preciob3);
            pos=pos+1;
        }
        if (this.postre1.equals("Manzana Templada")) {
            Ped.setValueAt(this.postre1, pos, 0);
            Ped.setValueAt(this.cantpo1, pos, 1);
            Ped.setValueAt(this.preciopo1, pos, 2);
            modificarArchivo(this.postre1 , this.cantpo1, this.preciopo1);
            pos=pos+1;
        }
        if (this.postre2.equals("Tiramisú Crujiente")) {
            Ped.setValueAt(this.postre2, pos, 0);
            Ped.setValueAt(this.cantpo2, pos, 1);
            Ped.setValueAt(this.preciopo2, pos, 2);
            modificarArchivo(this.postre2 , this.cantpo2, this.preciopo2);
            pos=pos+1;
        }
        if (this.postre3.equals("Exótico")) {
            Ped.setValueAt(this.postre3, pos, 0);
            Ped.setValueAt(this.cantpo3, pos, 1);
            Ped.setValueAt(this.preciopo3, pos, 2);
            modificarArchivo(this.postre3 , this.cantpo3, this.preciopo3);
            pos=pos+1;
        }
        if (this.postre4.equals("Minitarta Selva Negra")) {
            Ped.setValueAt(this.postre4, pos, 0);
            Ped.setValueAt(this.cantpo4, pos, 1);
            Ped.setValueAt(this.preciopo4, pos, 2);
            modificarArchivo(this.postre4 , this.cantpo4, this.preciopo4);
            pos = pos + 1;
        }
        Ped.setModel(model);
        modificarArchivo("", 1);
        modificarArchivo(horaP, 0);        
    }
    
    public void actualizarGM(){
        String ttpp = "" + tp;
        if (ttpp.length() < 4) {
            TP = TP + ttpp;
        }else{
            if(ttpp.length() == 4){//1.000
                TP = TP + ttpp.charAt(0) + "." + ttpp.substring(1, ttpp.length());
            }else{
                if (ttpp.length() == 5) {//10.000
                    TP = TP + ttpp.substring(0, 2) + "." + ttpp.substring(2, ttpp.length());
                }else{
                    if (ttpp.length() == 6) {//100.000
                        TP = TP + ttpp.charAt(0) + ttpp.charAt(1) + ttpp.charAt(2) + "." + ttpp.substring(3, ttpp.length());
                    }else{
                        if (ttpp.length() == 7) {//1'000.000
                            TP = TP + ttpp.charAt(0) + "'" + ttpp.substring(1, 4) + "." + ttpp.substring(4, ttpp.length());
                        }
                    }
                }
            }
        }
        horaPedido.setText("Hora en que se realizó el pedido: " + horaP);
        pedidoMesa.setText("Pedido de la mesa #: " + MesaN + ".");
        meseroCargo.setText("Mesero a cargo: " + nombreM + ".");
        totalPagar.setText("Total a pagar: " + TP + "$.");
        archivo = new File("C:\\Users\\user\\Documents\\NetBeansProjects\\Laboratorio\\src\\archivos\\Pedido" + MesaN + ".txt");
    }
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TiempoCoccion tc = new TiempoCoccion();
        tc.NomMesero = nombreM;
        tc.NumMesa = MesaN;
        tc.archivo = archivo;
        tc.m = 5 + ((int)(Math.random() * 10));
        tc.s = ((int)(Math.random() * 59));
        tc.tmc = tc.m - 5;
        tc.ma = (int)(Math.random() * (tc.m - 4));
        System.out.println(tc.ma + ":" + tc.sa);
        tc.actualizarCronometro();
        JOptionPane.showMessageDialog(null, "El plato tardará aproximadamente " + tc.m + ":" + tc.s + " cocinandose.", "TIEMPO DE COCCIÓN", INFORMATION_MESSAGE);
        System.out.println("Tiempo estimado de preparación = " + tc.m + ":" + tc.s);
        tc.setLocationRelativeTo(null);
        tc.setVisible(true);
        this.dispose();
        tc.crono.start();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void modificarArchivo(String horaPe, int c){
        try(FileWriter fw = new FileWriter(archivo, true)){
            Object hP = horaPe;
            if (c == 0) {
                fw.write("Hora a la que se realizó el pedido: " + hP + ".\r\n");
            }else{
                if(c == 1){
                    fw.write("Fin del pedido.\r\n");
                }else{
                    fw.write("Nombre del cliente: " + nombreC + ".\r\n");
                    fw.write("Cédula del cliente: " + cedulaC + ".\r\n");
                }
            }
            
        }catch(NullPointerException ex){
            
        }catch(IOException e){
            Logger.getLogger(Cocina.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void modificarArchivo(int mesa){
        try(FileWriter fw = new FileWriter(archivo, true)){
            Object mesaA = mesa;
            fw.write("Pedido:" + "\r\n");
        }catch(NullPointerException ex){
            
        }catch(IOException e){
            Logger.getLogger(Cocina.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void modificarArchivo(String plato, int cantidad, float precio){
        
        try(FileWriter bw = new FileWriter(archivo, true)){
            Object PL = plato;
            Object CA = cantidad;
            Object PR = precio;
            bw.write( PL + ", " + CA + ", " + PR + "\r" + "\n" );
        }catch(NullPointerException e){
        
        } catch (IOException ex) {
            Logger.getLogger(Cocina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cocina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Comanda;
    public javax.swing.JTable Ped;
    private javax.swing.JLabel horaPedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel meseroCargo;
    private javax.swing.JLabel pedidoMesa;
    private javax.swing.JLabel totalPagar;
    // End of variables declaration//GEN-END:variables
}
