package restaurante_la_prosperidad_camilo_miguel;

import java.util.*;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Calendar hora = new GregorianCalendar();
    Cocina pedido = new Cocina();
    public String nombreMesero, nombreCliente;
    public int cont=0, idMesa, cedulaCliente;
    
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Demostracion = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTODEMO = new javax.swing.JTextArea();
        IMAGENDEMO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PRECIOD = new javax.swing.JLabel();
        Demostracionpl = new javax.swing.JFrame();
        IMAGENDEMOPL = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PRECIODPL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TEXTODEMOPL = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        PKR = new javax.swing.JRadioButton();
        PPDC = new javax.swing.JRadioButton();
        KRP = new javax.swing.JLabel();
        PCP = new javax.swing.JLabel();
        PC1 = new javax.swing.JSpinner();
        PC2 = new javax.swing.JSpinner();
        PCCA = new javax.swing.JRadioButton();
        PSC = new javax.swing.JRadioButton();
        PSA = new javax.swing.JRadioButton();
        PC3 = new javax.swing.JSpinner();
        PC4 = new javax.swing.JSpinner();
        PC5 = new javax.swing.JSpinner();
        SRP = new javax.swing.JLabel();
        CAP = new javax.swing.JLabel();
        SCHP = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        KR = new javax.swing.JLabel();
        CCA = new javax.swing.JLabel();
        SCH = new javax.swing.JLabel();
        SAR = new javax.swing.JLabel();
        PPC = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        MTN = new javax.swing.JRadioButton();
        TCN = new javax.swing.JRadioButton();
        MTP = new javax.swing.JLabel();
        TCP = new javax.swing.JLabel();
        MTC = new javax.swing.JSpinner();
        TCC = new javax.swing.JSpinner();
        EN = new javax.swing.JRadioButton();
        MSNN = new javax.swing.JRadioButton();
        EC = new javax.swing.JSpinner();
        MSNC = new javax.swing.JSpinner();
        MSNP = new javax.swing.JLabel();
        EP = new javax.swing.JLabel();
        MSNI = new javax.swing.JLabel();
        MTI = new javax.swing.JLabel();
        TCI = new javax.swing.JLabel();
        EI = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BCC = new javax.swing.JRadioButton();
        BGS = new javax.swing.JRadioButton();
        GP = new javax.swing.JLabel();
        CCP = new javax.swing.JLabel();
        CCC = new javax.swing.JSpinner();
        GC = new javax.swing.JSpinner();
        BJN = new javax.swing.JRadioButton();
        JNC = new javax.swing.JSpinner();
        JNP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PedidoButton = new javax.swing.JButton();
        PAPA = new javax.swing.JLabel();
        CALCULAR = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        CANCELAR = new javax.swing.JButton();

        Demostracion.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Demostracion.setTitle("Demostracion");
        Demostracion.setMinimumSize(new java.awt.Dimension(420, 580));
        Demostracion.setResizable(false);
        Demostracion.setSize(new java.awt.Dimension(440, 580));
        Demostracion.setType(java.awt.Window.Type.POPUP);

        TEXTODEMO.setColumns(20);
        TEXTODEMO.setRows(5);
        TEXTODEMO.setText("¡Texto de prueba!");
        TEXTODEMO.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TEXTODEMO.setEnabled(false);
        TEXTODEMO.setFocusable(false);
        jScrollPane1.setViewportView(TEXTODEMO);

        jLabel2.setText("PRECIO POR UNIDAD:");

        PRECIOD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PRECIOD.setText("00.000,00$");

        javax.swing.GroupLayout DemostracionLayout = new javax.swing.GroupLayout(Demostracion.getContentPane());
        Demostracion.getContentPane().setLayout(DemostracionLayout);
        DemostracionLayout.setHorizontalGroup(
            DemostracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemostracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DemostracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DemostracionLayout.createSequentialGroup()
                        .addComponent(IMAGENDEMO, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DemostracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PRECIOD, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DemostracionLayout.setVerticalGroup(
            DemostracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DemostracionLayout.createSequentialGroup()
                .addGroup(DemostracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DemostracionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(IMAGENDEMO, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DemostracionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(PRECIOD)
                        .addGap(95, 95, 95)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        Demostracionpl.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Demostracionpl.setTitle("Demostracion");
        Demostracionpl.setMinimumSize(new java.awt.Dimension(530, 530));
        Demostracionpl.setResizable(false);
        Demostracionpl.setSize(new java.awt.Dimension(530, 530));

        IMAGENDEMOPL.setMaximumSize(new java.awt.Dimension(500, 277));
        IMAGENDEMOPL.setMinimumSize(new java.awt.Dimension(500, 277));
        IMAGENDEMOPL.setPreferredSize(new java.awt.Dimension(500, 277));

        jLabel11.setText("PRECIO POR UNIDAD:");

        PRECIODPL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PRECIODPL.setText("00.000,00$");

        TEXTODEMOPL.setEditable(false);
        TEXTODEMOPL.setColumns(20);
        TEXTODEMOPL.setRows(5);
        TEXTODEMOPL.setText("¡Texto de prueba!");
        TEXTODEMOPL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TEXTODEMOPL.setEnabled(false);
        TEXTODEMOPL.setFocusable(false);
        jScrollPane2.setViewportView(TEXTODEMOPL);

        javax.swing.GroupLayout DemostracionplLayout = new javax.swing.GroupLayout(Demostracionpl.getContentPane());
        Demostracionpl.getContentPane().setLayout(DemostracionplLayout);
        DemostracionplLayout.setHorizontalGroup(
            DemostracionplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemostracionplLayout.createSequentialGroup()
                .addGroup(DemostracionplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DemostracionplLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DemostracionplLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IMAGENDEMOPL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DemostracionplLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(DemostracionplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(DemostracionplLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(PRECIODPL, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DemostracionplLayout.setVerticalGroup(
            DemostracionplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemostracionplLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(IMAGENDEMOPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PRECIODPL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MENÚ");
        setMinimumSize(new java.awt.Dimension(640, 400));
        setPreferredSize(new java.awt.Dimension(640, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 400));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        PKR.setBackground(new java.awt.Color(255, 255, 255));
        PKR.setText("Kati Roll");
        PKR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PKRActionPerformed(evt);
            }
        });
        jPanel2.add(PKR);
        PKR.setBounds(10, 20, 200, 20);

        PPDC.setBackground(new java.awt.Color(255, 255, 255));
        PPDC.setText("Papada de Cerdo");
        PPDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPDCActionPerformed(evt);
            }
        });
        jPanel2.add(PPDC);
        PPDC.setBounds(10, 50, 200, 20);

        KRP.setText("30.700,00$");
        jPanel2.add(KRP);
        KRP.setBounds(340, 20, 80, 22);

        PCP.setText("37.000,00$");
        jPanel2.add(PCP);
        PCP.setBounds(340, 50, 80, 20);

        PC1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        PC1.setEnabled(false);
        PC1.setFocusable(false);
        jPanel2.add(PC1);
        PC1.setBounds(270, 20, 50, 22);

        PC2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        PC2.setEnabled(false);
        PC2.setFocusable(false);
        jPanel2.add(PC2);
        PC2.setBounds(270, 50, 50, 22);

        PCCA.setBackground(new java.awt.Color(255, 255, 255));
        PCCA.setText("Cabracho con Alcachofas");
        PCCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCCAActionPerformed(evt);
            }
        });
        jPanel2.add(PCCA);
        PCCA.setBounds(10, 80, 200, 20);

        PSC.setBackground(new java.awt.Color(255, 255, 255));
        PSC.setText("Solomillo de Cerdo Hojaldrado");
        PSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSCActionPerformed(evt);
            }
        });
        jPanel2.add(PSC);
        PSC.setBounds(10, 110, 200, 20);

        PSA.setBackground(new java.awt.Color(255, 255, 255));
        PSA.setText("Spaghetti al Ragú");
        PSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSAActionPerformed(evt);
            }
        });
        jPanel2.add(PSA);
        PSA.setBounds(10, 140, 200, 20);

        PC3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        PC3.setEnabled(false);
        PC3.setFocusable(false);
        jPanel2.add(PC3);
        PC3.setBounds(270, 80, 50, 22);

        PC4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        PC4.setEnabled(false);
        PC4.setFocusable(false);
        jPanel2.add(PC4);
        PC4.setBounds(270, 110, 50, 22);

        PC5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        PC5.setEnabled(false);
        PC5.setFocusable(false);
        jPanel2.add(PC5);
        PC5.setBounds(270, 140, 50, 22);

        SRP.setText("28.000,00$");
        jPanel2.add(SRP);
        SRP.setBounds(340, 140, 80, 22);

        CAP.setText("40.000,00$");
        jPanel2.add(CAP);
        CAP.setBounds(340, 80, 80, 20);

        SCHP.setText("35.800,00$");
        jPanel2.add(SCHP);
        SCHP.setBounds(340, 110, 80, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PLATOS");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 420, 20);

        KR.setBackground(new java.awt.Color(0, 0, 0));
        KR.setForeground(new java.awt.Color(51, 0, 51));
        KR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        KR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        KR.setMaximumSize(new java.awt.Dimension(283, 404));
        KR.setMinimumSize(new java.awt.Dimension(283, 404));
        KR.setPreferredSize(new java.awt.Dimension(283, 404));
        KR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KRMouseClicked(evt);
            }
        });
        jPanel2.add(KR);
        KR.setBounds(230, 20, 20, 20);

        CCA.setBackground(new java.awt.Color(0, 0, 0));
        CCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        CCA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CCA.setMaximumSize(new java.awt.Dimension(283, 404));
        CCA.setMinimumSize(new java.awt.Dimension(283, 404));
        CCA.setPreferredSize(new java.awt.Dimension(283, 404));
        CCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CCAMouseClicked(evt);
            }
        });
        jPanel2.add(CCA);
        CCA.setBounds(230, 80, 20, 20);

        SCH.setBackground(new java.awt.Color(0, 0, 0));
        SCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        SCH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SCH.setMaximumSize(new java.awt.Dimension(283, 404));
        SCH.setMinimumSize(new java.awt.Dimension(283, 404));
        SCH.setPreferredSize(new java.awt.Dimension(283, 404));
        SCH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SCHMouseClicked(evt);
            }
        });
        jPanel2.add(SCH);
        SCH.setBounds(230, 110, 20, 20);

        SAR.setBackground(new java.awt.Color(0, 0, 0));
        SAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        SAR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SAR.setPreferredSize(new java.awt.Dimension(283, 404));
        SAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SARMouseClicked(evt);
            }
        });
        jPanel2.add(SAR);
        SAR.setBounds(230, 140, 20, 20);

        PPC.setBackground(new java.awt.Color(0, 0, 0));
        PPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        PPC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PPC.setMaximumSize(new java.awt.Dimension(283, 404));
        PPC.setMinimumSize(new java.awt.Dimension(283, 404));
        PPC.setPreferredSize(new java.awt.Dimension(283, 404));
        PPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PPCMouseClicked(evt);
            }
        });
        jPanel2.add(PPC);
        PPC.setBounds(230, 50, 20, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(190, 10, 420, 170);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(null);

        MTN.setBackground(new java.awt.Color(255, 255, 255));
        MTN.setText("Manzana Templada");
        MTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTNActionPerformed(evt);
            }
        });
        jPanel3.add(MTN);
        MTN.setBounds(5, 20, 140, 22);

        TCN.setBackground(new java.awt.Color(255, 255, 255));
        TCN.setText("Tiramisú Crujiente");
        TCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCNActionPerformed(evt);
            }
        });
        jPanel3.add(TCN);
        TCN.setBounds(5, 45, 140, 22);

        MTP.setText("8.300,00$");
        jPanel3.add(MTP);
        MTP.setBounds(250, 20, 65, 22);

        TCP.setText("11.800,00$");
        jPanel3.add(TCP);
        TCP.setBounds(250, 45, 65, 22);

        MTC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        MTC.setEnabled(false);
        MTC.setFocusable(false);
        jPanel3.add(MTC);
        MTC.setBounds(180, 20, 65, 22);

        TCC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        TCC.setEnabled(false);
        TCC.setFocusable(false);
        jPanel3.add(TCC);
        TCC.setBounds(180, 45, 65, 22);

        EN.setBackground(new java.awt.Color(255, 255, 255));
        EN.setText("Exótico");
        EN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENActionPerformed(evt);
            }
        });
        jPanel3.add(EN);
        EN.setBounds(5, 70, 140, 22);

        MSNN.setBackground(new java.awt.Color(255, 255, 255));
        MSNN.setText("Minitarta Selva Negra");
        MSNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSNNActionPerformed(evt);
            }
        });
        jPanel3.add(MSNN);
        MSNN.setBounds(5, 95, 140, 22);

        EC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        EC.setEnabled(false);
        EC.setFocusable(false);
        jPanel3.add(EC);
        EC.setBounds(180, 70, 65, 22);

        MSNC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        MSNC.setEnabled(false);
        MSNC.setFocusable(false);
        jPanel3.add(MSNC);
        MSNC.setBounds(180, 95, 65, 22);

        MSNP.setText("16.200,00$");
        jPanel3.add(MSNP);
        MSNP.setBounds(250, 95, 65, 22);

        EP.setText("9.700,00$");
        jPanel3.add(EP);
        EP.setBounds(250, 70, 65, 22);

        MSNI.setBackground(new java.awt.Color(0, 0, 0));
        MSNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        MSNI.setText("   ");
        MSNI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        MSNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MSNIMouseClicked(evt);
            }
        });
        jPanel3.add(MSNI);
        MSNI.setBounds(150, 95, 20, 20);

        MTI.setBackground(new java.awt.Color(0, 0, 0));
        MTI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        MTI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        MTI.setMaximumSize(new java.awt.Dimension(283, 404));
        MTI.setMinimumSize(new java.awt.Dimension(283, 404));
        MTI.setPreferredSize(new java.awt.Dimension(283, 404));
        MTI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MTIMouseClicked(evt);
            }
        });
        jPanel3.add(MTI);
        MTI.setBounds(150, 20, 20, 20);

        TCI.setBackground(new java.awt.Color(0, 0, 0));
        TCI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        TCI.setText("   ");
        TCI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TCI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TCIMouseClicked(evt);
            }
        });
        jPanel3.add(TCI);
        TCI.setBounds(150, 45, 20, 20);

        EI.setBackground(new java.awt.Color(0, 0, 0));
        EI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg"))); // NOI18N
        EI.setText("   ");
        EI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EIMouseClicked(evt);
            }
        });
        jPanel3.add(EI);
        EI.setBounds(150, 70, 20, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("POSTRES");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(1, 1, 318, 14);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 190, 320, 120);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(null);

        BCC.setBackground(new java.awt.Color(255, 255, 255));
        BCC.setText("Coca Cola");
        BCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCCActionPerformed(evt);
            }
        });
        jPanel4.add(BCC);
        BCC.setBounds(10, 20, 100, 22);

        BGS.setBackground(new java.awt.Color(255, 255, 255));
        BGS.setText("Gaseosa");
        BGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGSActionPerformed(evt);
            }
        });
        jPanel4.add(BGS);
        BGS.setBounds(10, 50, 100, 22);

        GP.setText("1.900,00$");
        jPanel4.add(GP);
        GP.setBounds(190, 50, 65, 22);

        CCP.setText("2.000,00$");
        jPanel4.add(CCP);
        CCP.setBounds(190, 20, 65, 22);

        CCC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        CCC.setEnabled(false);
        CCC.setFocusable(false);
        jPanel4.add(CCC);
        CCC.setBounds(130, 20, 50, 22);

        GC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        GC.setEnabled(false);
        GC.setFocusable(false);
        jPanel4.add(GC);
        GC.setBounds(130, 50, 50, 22);

        BJN.setBackground(new java.awt.Color(255, 255, 255));
        BJN.setText("Jugos Naturales");
        BJN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJNActionPerformed(evt);
            }
        });
        jPanel4.add(BJN);
        BJN.setBounds(10, 80, 120, 22);

        JNC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        JNC.setEnabled(false);
        JNC.setFocusable(false);
        jPanel4.add(JNC);
        JNC.setBounds(130, 80, 50, 22);

        JNP.setText("1.800,00$");
        jPanel4.add(JNP);
        JNP.setBounds(190, 80, 65, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BEBIDAS");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(1, 1, 258, 14);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 190, 260, 120);

        PedidoButton.setText("HACER PEDIDO");
        PedidoButton.setEnabled(false);
        PedidoButton.setVisible(false);
        PedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PedidoButton);
        PedidoButton.setBounds(190, 320, 140, 23);

        PAPA.setBackground(new java.awt.Color(255, 255, 255));
        PAPA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(PAPA);
        PAPA.setBounds(10, 340, 370, 20);

        CALCULAR.setText("CALCULAR");
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(CALCULAR);
        CALCULAR.setBounds(510, 320, 100, 23);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/menu4.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 10, 170, 170);

        CANCELAR.setText("CANCELAR PEDIDO");
        CANCELAR.setEnabled(false);
        CANCELAR.setVisible(false);
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });
        getContentPane().add(CANCELAR);
        CANCELAR.setBounds(340, 320, 160, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MTIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MTIMouseClicked
        IMAGENDEMO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre1.jpg")));
        TEXTODEMO.setText("MANZANA TEMPLADA\n" +
        "Frenchipan de almendras y manzana caramelizada con miel y licor.");
        PRECIOD.setText("8.300,00$");
        Demostracion.setLocationRelativeTo(null);
        Demostracion.setVisible(true);
    }//GEN-LAST:event_MTIMouseClicked

    private void TCIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TCIMouseClicked
        IMAGENDEMO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre2.jpg")));
        TEXTODEMO.setText("TIRAMISÚ CRUJIENTE\n" +
        "Laminas finas de chocolate amargo, bizcocho tierno de almendras\n"
        + "aromatizado con licor de café crema fina de dos quesos y\ncrema fina de dos quesos con café.\n\n" +
        "Postre con un aspecto muy artesanal muy suave en boca y con\n"
        + "aromas a café de Colombia.");
        PRECIOD.setText("11.800,00$");
        Demostracion.setLocationRelativeTo(null);
        Demostracion.setVisible(true);
    }//GEN-LAST:event_TCIMouseClicked
    
    private void EIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EIMouseClicked
        IMAGENDEMO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre3.jpg")));
        TEXTODEMO.setText("EXÓTICO\n" +
        "Bizcocho clasico,mermelada de frutas rojas artesana, mousse de\nmango y fruta de la pasión gelatina de maracuyá.\n" +
        "Las combinación de sabores exóticos y las frutas del bosque\nprovocan una sensación divertida a la hora de degustar este postre\nsin olvidar su frescura.");
        PRECIOD.setText("9.700,00$");
        Demostracion.setLocationRelativeTo(null);
        Demostracion.setVisible(true);
    }//GEN-LAST:event_EIMouseClicked

    private void MSNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSNIMouseClicked
        IMAGENDEMO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Postre4.jpg")));
        TEXTODEMO.setText("MINITARTA SELVA NEGRA\n" +
        "Bizcocho de almendras, nata, mermelada de frutas rojas, trufa y\nvirutas de chocolate.\n\n" +
        "Es un clásico y típico pero no debe faltar en una buena carta de\npostres por su calidad de ingredientes.");
        PRECIOD.setText("16.200,00$");
        Demostracion.setLocationRelativeTo(null);
        Demostracion.setVisible(true);        
    }//GEN-LAST:event_MSNIMouseClicked

    int pt;
    private void CALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARActionPerformed
        pt =  (((int)PC1.getValue()* 30700) + ((int)PC2.getValue()* 37000) + ((int)PC4.getValue()* 35800) + ((int)PC3.getValue()*40000)+((int)PC5.getValue()*28000) + ((int)CCC.getValue() * 2000) + ((int)GC.getValue() * 1900) + ((int)JNC.getValue() * 1800)) + (((int)MTC.getValue()*8300) + ((int)TCC.getValue() * 11800) + ((int)EC.getValue()*9700) + ((int)MSNC.getValue())*16200);
        if(pt != 0){
            PAPA.setText("Precio a pagar sin IVA: " + Integer.toString(pt) + ",00$");
            PedidoButton.setVisible(true);
            PedidoButton.setEnabled(true);
            CANCELAR.setText("CAMBIAR PEDIDO");
        }else{
            PAPA.setText("Presione cancelar y haga bien el pedido.");
        }
        CANCELAR.setVisible(true);
        CANCELAR.setEnabled(true);
        CALCULAR.setEnabled(false);
    }//GEN-LAST:event_CALCULARActionPerformed

    private void PKRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PKRActionPerformed
        if (PKR.isSelected()==true){
          PC1.setValue(1);
          PC1.setEnabled(true);
        }
        if (PKR.isSelected()!=true){
          PC1.setValue(0);
          PC1.setEnabled(false);
        }
    }//GEN-LAST:event_PKRActionPerformed

    private void PCCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCCAActionPerformed
        if (PCCA.isSelected()==true){
          PC3.setValue(1);
          PC3.setEnabled(true);
        }
        if (!PCCA.isSelected()==true){
          PC3.setValue(0);
          PC3.setEnabled(false);
        }
    }//GEN-LAST:event_PCCAActionPerformed

    private void PPDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPDCActionPerformed
        if (PPDC.isSelected()==true){
          PC2.setValue(1);
          PC2.setEnabled(true);
        }
        if (!PPDC.isSelected()==true){
          PC2.setValue(0);
          PC2.setEnabled(false);
        }
    }//GEN-LAST:event_PPDCActionPerformed

    private void PSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSCActionPerformed
        if (PSC.isSelected()==true){
          PC4.setValue(1);
          PC4.setEnabled(true);
        }
        if (!PSC.isSelected()==true){
          PC4.setValue(0);
          PC4.setEnabled(false);
        }
    }//GEN-LAST:event_PSCActionPerformed
    //1
    private void KRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KRMouseClicked
        IMAGENDEMOPL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Plato1.jpg")));
        TEXTODEMOPL.setText(" KATI ROLL\n\n"+
        "Kati Roll es una brocheta de pollo o cordero marinado en especias, \nenvuelto en un pan paratha y freido parcialmente en aceite en una plancha.");
        PRECIODPL.setText("30.700,00$");
        Demostracionpl.setLocationRelativeTo(null);
        Demostracionpl.setVisible(true);  
    }//GEN-LAST:event_KRMouseClicked
    //4
    private void SCHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SCHMouseClicked
        IMAGENDEMOPL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Plato4.jpg")));
        TEXTODEMOPL.setText("SOLOMILLO DE CERDO HOJALDRADO\n\n"
                + "Este Solomillo de cerdo hojaldrado está relleno de setas, \npimientos asados y caramelizados, Aderezado con un hilo \nde salsa de Mostaza ");
        PRECIODPL.setText("40.000,00$");
        Demostracionpl.setLocationRelativeTo(null);
        Demostracionpl.setVisible(true); 
    }//GEN-LAST:event_SCHMouseClicked
    //2
    private void PPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPCMouseClicked
        IMAGENDEMOPL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Plato2.jpg")));
        TEXTODEMOPL.setText("PAPADA DE CERDO\n\n"
        + "Cerdo adobado con orégano, albahaca y pimienta, \ncortado en trozos cuadrados y cubierto en salsa de tamarindo.");
        PRECIODPL.setText("37.000,00$");
        Demostracionpl.setLocationRelativeTo(null);
        Demostracionpl.setVisible(true); 
    }//GEN-LAST:event_PPCMouseClicked
    
    private void CCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCAMouseClicked
        IMAGENDEMOPL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Plato3.jpg")));
        TEXTODEMOPL.setText("CABRACHO CON ALCACHOFAS\n\n"+
        "Filete de cabracho a la plancha rociado con alcachofas \npreviamente horneadas con sal, pimienta, un poco de acite y vinagre.");
        PRECIODPL.setText("35.800,00$");
        Demostracionpl.setLocationRelativeTo(null);
        Demostracionpl.setVisible(true); 
    }//GEN-LAST:event_CCAMouseClicked
    //5
    private void SARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SARMouseClicked
        IMAGENDEMOPL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Plato5.jpg")));
        TEXTODEMOPL.setText("SPAGHETTI AL RAGÚ\n\n"
        + "Spaghetti bañado en salsa Ragú, la cual es una salsa hecha a base \nde tomate, zanahoria y cebolla, todo sofrito y reducido con vino, ademas \nse le agrega a las pastas un poco de queso espolvoreado por encima.");
        PRECIODPL.setText("28.000,00$");
        Demostracionpl.setLocationRelativeTo(null);
        Demostracionpl.setVisible(true); 
    }//GEN-LAST:event_SARMouseClicked

    private void PedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoButtonActionPerformed
        if (PKR.isSelected()==true) {
            pedido.plato1 = PKR.getText();
            pedido.cantpl1 = (int)PC1.getValue();
            pedido.preciopl1 = 30700;
            this.cont=this.cont+1;
        }
        if (PPDC.isSelected()==true) {
            pedido.plato2 = PPDC.getText();
            pedido.cantpl2= (int) PC2.getValue();
            pedido.preciopl2 = 37000;
            this.cont=this.cont+1;
        }
        if (PCCA.isSelected()==true) {
            pedido.plato3= PCCA.getText();
            pedido.cantpl3 = (int)PC3.getValue();
            pedido.preciopl3 = 35800;
            this.cont=this.cont+1;
        }
        if (PSC.isSelected()==true) {
            pedido.plato4= PSC.getText();
            pedido.cantpl4 = (int)PC4.getValue();
            pedido.preciopl4 = 40000;
            this.cont=this.cont+1;
        }
        if (PSA.isSelected()==true) {
            pedido.plato5= PSA.getText();
            pedido.cantpl5 = (int)PC5.getValue();
            pedido.preciopl5 = 28000;
            this.cont=this.cont+1;
        }
        if (BCC.isSelected()==true) {
            pedido.bebida1= BCC.getText();
            pedido.cantb1 = (int)CCC.getValue();
            pedido.preciob1 = 2000;
            this.cont=this.cont+1;
        }
        if (BGS.isSelected()==true) {
            pedido.bebida2= BGS.getText();
            pedido.cantb2 = (int)GC.getValue();
            pedido.preciob2 = 1900;
            this.cont=this.cont+1;
        }
        if (BJN.isSelected()==true) {
            pedido.bebida3= BJN.getText();
            pedido.cantb3 = (int)JNC.getValue();
            pedido.preciob3 = 1800;
            this.cont=this.cont+1;
        }
        if (MTN.isSelected()==true) {
            pedido.postre1= MTN.getText();
            pedido.cantpo1 = (int)MTC.getValue();
            pedido.preciopo1 = 8300;
            this.cont=this.cont+1;
        }
        if (TCN.isSelected()==true) {
            pedido.postre2= TCN.getText();
            pedido.cantpo2 = (int)TCC.getValue();
            pedido.preciopo2 = 11800;
            this.cont=this.cont+1;
        }
        if (EN.isSelected()==true) {
            pedido.postre3= EN.getText();
            pedido.cantpo3 = (int)EC.getValue();
            pedido.preciopo3 = 9700;
            this.cont=this.cont+1;
        }
        if (MSNN.isSelected()==true) {
            pedido.postre4 = MSNN.getText();
            pedido.cantpo4 = (int)MSNC.getValue();
            pedido.preciopo4 = 16200;
            this.cont=this.cont+1;
        }
        pedido.cont = this.cont;
        pedido.MesaN = idMesa;
        pedido.nombreM = nombreMesero;
        pedido.nombreC = nombreCliente;
        pedido.cedulaC = cedulaCliente;
        this.dispose();
        pedido.tp = pt;
        int hh = hora.get(Calendar.HOUR_OF_DAY), mm = hora.get(Calendar.MINUTE), ss = hora.get(Calendar.SECOND);
        pedido.horaP = (hh < 10?"0":"") + hh + ":" + (mm < 10?"0":"") + mm + ":" + (ss < 10?"0":"") + ss;
        System.out.println(pedido.horaP);
        pedido.actualizarGM();
        pedido.generarMatriz();        
        pedido.setVisible(true);
        pedido.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_PedidoButtonActionPerformed

    private void PSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSAActionPerformed
        if (PSA.isSelected() == true){
          PC5.setValue(1);
          PC5.setEnabled(true);
        }
        if (!PSA.isSelected() == true){
          PC5.setValue(0);
          PC5.setEnabled(false);
        }
    }//GEN-LAST:event_PSAActionPerformed

    private void BCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCCActionPerformed
        if (BCC.isSelected() == true){
          CCC.setValue(1);
          CCC.setEnabled(true);
        }
        if (!BCC.isSelected()== true){
          CCC.setValue(0);
          CCC.setEnabled(false);
        }
    }//GEN-LAST:event_BCCActionPerformed

    private void BGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGSActionPerformed
        if (BGS.isSelected()==true){
          GC.setValue(1);
          GC.setEnabled(true);
        }
        if (!BGS.isSelected()==true){
          GC.setValue(0);
          GC.setEnabled(false);
        }
    }//GEN-LAST:event_BGSActionPerformed

    private void BJNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJNActionPerformed
        if (BJN.isSelected()==true){
          JNC.setValue(1);
          JNC.setEnabled(true);
        }
        if (!BJN.isSelected()==true){
          JNC.setValue(0);
          JNC.setEnabled(false);
        }
    }//GEN-LAST:event_BJNActionPerformed

    private void MTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTNActionPerformed
        if (MTN.isSelected()==true){
          MTC.setValue(1);
          MTC.setEnabled(true);
        }
        if (!MTN.isSelected()==true){
          MTC.setValue(0);
          MTC.setEnabled(false);
        }
    }//GEN-LAST:event_MTNActionPerformed

    private void TCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCNActionPerformed
        if (TCN.isSelected()==true){
          TCC.setValue(1);
          TCC.setEnabled(true);
        }
        if (!TCN.isSelected()==true){
          TCC.setValue(0);
          TCC.setEnabled(false);
        }
    }//GEN-LAST:event_TCNActionPerformed

    private void ENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENActionPerformed
        if (EN.isSelected()==true){
          EC.setValue(1);
          EC.setEnabled(true);
        }
        if (!EN.isSelected()==true){
          EC.setValue(0);
          EC.setEnabled(false);
        }

    }//GEN-LAST:event_ENActionPerformed

    private void MSNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSNNActionPerformed
        if (MSNN.isSelected()==true){
          MSNC.setValue(1);
          MSNC.setEnabled(true);
        }
        if (!MSNN.isSelected()==true){
          MSNC.setValue(0);
          MSNC.setEnabled(false);
        }
    }//GEN-LAST:event_MSNNActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        Menu menu = new Menu();
        menu.idMesa = idMesa;
        menu.nombreMesero = nombreMesero;
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CANCELARActionPerformed
    //se crea una jframe interno en el cuan contiene la factura con los pedidos que realizo y un joption para mostrar que ya pago.    //se crea una jframe interno en el cuan contiene la factura con los pedidos que realizo y un joption para mostrar que ya pago.
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
// <editor-fold defaultstate="collapsed" desc="Variables">       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BCC;
    private javax.swing.JRadioButton BGS;
    private javax.swing.JRadioButton BJN;
    private javax.swing.JButton CALCULAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JLabel CAP;
    private javax.swing.JLabel CCA;
    private javax.swing.JSpinner CCC;
    private javax.swing.JLabel CCP;
    private javax.swing.JFrame Demostracion;
    private javax.swing.JFrame Demostracionpl;
    private javax.swing.JSpinner EC;
    private javax.swing.JLabel EI;
    private javax.swing.JRadioButton EN;
    private javax.swing.JLabel EP;
    private javax.swing.JSpinner GC;
    private javax.swing.JLabel GP;
    private javax.swing.JLabel IMAGENDEMO;
    private javax.swing.JLabel IMAGENDEMOPL;
    private javax.swing.JSpinner JNC;
    private javax.swing.JLabel JNP;
    private javax.swing.JLabel KR;
    private javax.swing.JLabel KRP;
    private javax.swing.JSpinner MSNC;
    private javax.swing.JLabel MSNI;
    private javax.swing.JRadioButton MSNN;
    private javax.swing.JLabel MSNP;
    private javax.swing.JSpinner MTC;
    private javax.swing.JLabel MTI;
    private javax.swing.JRadioButton MTN;
    private javax.swing.JLabel MTP;
    private javax.swing.JLabel PAPA;
    private javax.swing.JSpinner PC1;
    private javax.swing.JSpinner PC2;
    private javax.swing.JSpinner PC3;
    private javax.swing.JSpinner PC4;
    private javax.swing.JSpinner PC5;
    private javax.swing.JRadioButton PCCA;
    private javax.swing.JLabel PCP;
    private javax.swing.JRadioButton PKR;
    private javax.swing.JLabel PPC;
    private javax.swing.JRadioButton PPDC;
    private javax.swing.JLabel PRECIOD;
    private javax.swing.JLabel PRECIODPL;
    private javax.swing.JRadioButton PSA;
    private javax.swing.JRadioButton PSC;
    private javax.swing.JButton PedidoButton;
    private javax.swing.JLabel SAR;
    private javax.swing.JLabel SCH;
    private javax.swing.JLabel SCHP;
    private javax.swing.JLabel SRP;
    private javax.swing.JSpinner TCC;
    private javax.swing.JLabel TCI;
    private javax.swing.JRadioButton TCN;
    private javax.swing.JLabel TCP;
    private javax.swing.JTextArea TEXTODEMO;
    private javax.swing.JTextArea TEXTODEMOPL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
//</editor-fold>