package restaurante_la_prosperidad_camilo_miguel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.Timer;

public class TiempoCoccion extends javax.swing.JFrame {
    int Minutos, Segundos;
    File archivo;
    ActionListener repeticion = new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent AE) {
            s++;
            if(s == 60){
                s = 0;
                m = m + 1;
            }
            if(m == 60){
                m = 0;
                h = h + 1;
            }
            if(h == 24){
                crono.stop();
            }
            if (m >= 5) {
                cancelarP.setEnabled(false);
            }
            if (Minutos == m && Segundos == s) {
                crono.stop();
                JOptionPane.showMessageDialog(null, "El plato está listo para ser servido.", "PLATO LISTO", INFORMATION_MESSAGE);
            }
            actualizarCronometro();
        }
        
    };
    int NumMesa;
    String NomMesero;
    int h = 0, m = 0, s = 0;
    String tiempo;
    Timer crono = new Timer(1000, repeticion);
    public void actualizarCronometro(){
        tiempo = (h < 10?"0":"") + h + ":" + (m < 10?"0":"") + m + ":" + (s < 10? "0":"") + s; //(h < 10? "0":"") Sirve para agregar un tipo de valor, es decir si es menor que 10 se vera asi = 08 y si es mayor a 10 = 11;
        tiempoC.setText(tiempo);
        if(m == Minutos && s == Segundos){
            this.dispose(); 
        }
    }
    /**
     * Creates new form Tiempococcionn
     */
    public TiempoCoccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tiempoC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cancelarP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tiempoC.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        tiempoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoC.setText("00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiempoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiempoC, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("El plato estará listo dentro de: ");

        cancelarP.setText("CANCELAR PEDIDO");
        cancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(cancelarP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarP)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPActionPerformed
        int R = JOptionPane.showConfirmDialog(null, "¿Desea cambiar el pedido?\nSe le mostrará nuevamente el menú si elige [ SI ]", "CANCELAR PEDIDO", YES_NO_CANCEL_OPTION);
        if (R == 0) {
            crono.stop();
            Menú menu = new Menú();
            menu.idMesa = NumMesa;
            menu.nombreMesero = NomMesero;
            archivo.delete();
            menu.setVisible(true);
            this.dispose();
        }        
    }//GEN-LAST:event_cancelarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiempoCoccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiempoCoccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiempoCoccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiempoCoccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiempoCoccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarP;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tiempoC;
    // End of variables declaration//GEN-END:variables
}
